name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pcov, curl, xml, zip, mbstring, json

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install packages with composer
        run: composer install

      - name: Run tests, static type checker and linter
        run: composer github

      - name: Upload coverage report to Codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh)
        env:
          CODACY_API_TOKEN: ${{secrets.CODACY_ACCOUNT_TOKEN}}
          CODACY_ORGANIZATION_PROVIDER: gh
          CODACY_USERNAME: vacantplanet
          CODACY_PROJECT_NAME: boiler
